//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace channelAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelsType
    {
        public int Id_ChanType { get; set; }
        public string ChannelType_Ar { get; set; }
        public string ChannelType_En { get; set; }
        public string ChanTypeAddedBy { get; set; }
        public Nullable<System.DateTime> ChanTypeAddedDT { get; set; }
        public string ChanTypeEditedBy { get; set; }
        public Nullable<System.DateTime> ChanTypeEditedDT { get; set; }
        public string ChanTypeDeletedBy { get; set; }
        public Nullable<System.DateTime> ChanTypeDeletedDate { get; set; }
        public string ChanTypeIsDeleted { get; set; }
        public string ChanTypeIsPublished { get; set; }
    }
}
