//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace channelAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channels_SRs
    {
        public int Id_chanSR { get; set; }
        public string chanSR { get; set; }
        public string chanSRAddedBy { get; set; }
        public Nullable<System.DateTime> chanSRAddedDT { get; set; }
        public string chanSREditedBy { get; set; }
        public Nullable<System.DateTime> chanSREditedDT { get; set; }
        public string chanSRDeletedBy { get; set; }
        public Nullable<System.DateTime> chanSRDeletedDate { get; set; }
        public string chanSRIsPublished { get; set; }
        public string chanSRIsDeleted { get; set; }
    }
}
