//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace channelAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoveringArea
    {
        public int Id_covArea { get; set; }
        public string covAreaName_Ar { get; set; }
        public string covAreaName_En { get; set; }
        public Nullable<double> covAreaLongFrom { get; set; }
        public Nullable<double> covAreaLongTo { get; set; }
        public string covAreaOrienFrom { get; set; }
        public string covAreaOrienTo { get; set; }
        public string covAreaCountries { get; set; }
        public string covAreaAddedByUsID { get; set; }
        public Nullable<System.DateTime> covAreaAddedDt { get; set; }
        public string covAreaEdtdByUsID { get; set; }
        public Nullable<System.DateTime> covAreaEdtDt { get; set; }
        public string covAreaDeletedByUsID { get; set; }
        public Nullable<System.DateTime> covAreaDeletedDt { get; set; }
        public string covAreaIsDeleted { get; set; }
        public string covAreaIsPublished { get; set; }
    }
}
