//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace channelAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequencies_Owners
    {
        public int Id_owner { get; set; }
        public string ownerName_Ar { get; set; }
        public string ownerName_En { get; set; }
        public string logoLink { get; set; }
        public string ownerAdd_Ar { get; set; }
        public string ownerAdd_En { get; set; }
        public string ownerAddedByUsID { get; set; }
        public Nullable<System.DateTime> ownerAddedDt { get; set; }
        public string ownerEdtdByUsID { get; set; }
        public Nullable<System.DateTime> ownerEdtDt { get; set; }
        public string ownerDeletedByUsID { get; set; }
        public Nullable<System.DateTime> ownerDeletedDt { get; set; }
        public string ownerIsDeleted { get; set; }
        public string ownerIsPublished { get; set; }
    }
}
