//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace channelAplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogosLink
    {
        public string folderName { get; set; }
        public string logosLinks { get; set; }
        public string logosLinksAddedBy { get; set; }
        public Nullable<System.DateTime> logosLinksAddedDT { get; set; }
        public string logosLinksEditedBy { get; set; }
        public Nullable<System.DateTime> logosLinksEditedDT { get; set; }
        public string logosLinksDeletedBy { get; set; }
        public Nullable<System.DateTime> logosLinksDeletedDT { get; set; }
        public string logosLinksIsPublished { get; set; }
        public string logosLinksIsDeleted { get; set; }
        public int Id_logoslinks { get; set; }
    }
}
